{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23414] Issue with network connection", "trace": "('C:\\\\Users\\\\FOMSI\\\\OneDrive\\\\Рабочий стол\\\\lesson_pyTest\\\\tests\\\\users\\\\test_users.py', 19, 'Skipped: [ISSUE-23414] Issue with network connection')"}, "start": 1677606256947, "stop": 1677606256947, "uuid": "e515b81b-4555-41f3-a263-70174a4e4bff", "historyId": "ecdad97ca3d7a3be9fe1de0e65fa7b4f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23414] Issue with network connection')"}, {"name": "tag", "value": "production"}, {"name": "tag", "value": "development"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "DESKTOP-GO0B47L"}, {"name": "thread", "value": "4020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}