{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23414] Issue with network connection", "trace": "('C:\\\\Users\\\\FOMSI\\\\OneDrive\\\\Рабочий стол\\\\lesson_pyTest\\\\tests\\\\users\\\\test_users.py', 19, 'Skipped: [ISSUE-23414] Issue with network connection')"}, "description": "\n    In that test we try to check that 1 is equal to 2\n    ", "start": 1677607607883, "stop": 1677607607883, "uuid": "3bf7a5ea-c558-474a-8ea3-969a5980d31e", "historyId": "ecdad97ca3d7a3be9fe1de0e65fa7b4f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23414] Issue with network connection')"}, {"name": "tag", "value": "production"}, {"name": "tag", "value": "development"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "DESKTOP-GO0B47L"}, {"name": "thread", "value": "7256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}